export const languages = {
    en: 'English',
    bg: 'Български',
};

export const defaultLang = 'bg';

export const ui = {
    en: {
        'nav.about': 'About Me',
        'nav.products': 'Products',
        'nav.lab': 'The Lab',
        'nav.work_with_us': 'Work With Us',
        'hero.title.prefix': 'Architecting',
        'hero.title.suffix': 'Digital Ventures',
        'hero.led_by': 'Led by Kalin Dimitrov',
        'hero.description': 'Invent2025 is a <strong>Product Engineering Lab</strong> that bridges the gap between academic research and battle-tested Angular SaaS. We build scalable platforms for the future.',
        'hero.learn_more': 'Learn More About Kalin →',
        'services.title': 'Client Services',
        'services.architecture.title': 'System Architecture',
        'services.architecture.desc': 'Optimization of large-scale Angular/Nx monorepos.',
        'services.mvp.title': 'MVP Development',
        'services.mvp.desc': 'Full-cycle: Design, Code, Deploy.',
        'ventures.title': 'Our Ventures',
        'ventures.subtitle': 'SAAS & PLUGINS',
        'ventures.view_all': 'View All →',
        'ventures.inviteathon.desc': 'B2B SaaS for Party Centers.',
        'ventures.inviteathon.users': '10,000+ Users.',
        'ventures.inviteathon.live': 'LIVE',
        'ventures.ascendpass.desc': 'Membership system active with real-world clients.',
        'ventures.ascendpass.live': 'LIVE SAAS',
        'ascendpass.status.live': 'Active in Production',
        'ascendpass.subtitle': 'Memberships & Subscriptions',
        'ascendpass.platform.title': 'The Platform',
        'ascendpass.platform.desc': 'Managing recurring revenue and access control requires extreme reliability. AscendPass is a comprehensive membership solution already powering live businesses.',
        'ascendpass.platform.desc2': 'It manages the entire lifecycle: from the moment a user signs up, through monthly recurring payments, to role-based access control in the client application.',
        'ascendpass.billing.title': 'Automated Billing',
        'ascendpass.billing.desc': 'Deep Stripe integration for failed payment recovery, pro-rations, and upgrades.',
        'ascendpass.rbac.title': 'RBAC & Auth',
        'ascendpass.rbac.desc': 'Granular permission scopes that sync instantly with subscription status.',
        'ventures.plugin.desc': 'Automated database migration and dual price display for WooCommerce.',
        'ventures.view_case_study': 'View Case Study →',
        'ventures.view_platform': 'View Platform →',
        'ventures.view_product': 'View Product →',
        'lab.title': 'From The Lab',
        'lab.view_all': 'View All →',
        'lab.case_study': 'Case Study',
        'lab.engineering': 'Engineering',
        'lab.research': 'Research',
        'cta.title': "Let's build.",
        'cta.subtitle': 'Need a System Architect?',
        'cta.button': 'Book Context',
        'footer.rights': 'All rights reserved.',
        'plugin.hero.tag': 'WOOCOMMERCE PLUGIN',
        'plugin.hero.title': 'Prepare for the Euro.',
        'plugin.hero.desc': 'Automate your store\'s transition from BGN to EUR with fixed BNB rates. Display dual prices today, convert efficiently tomorrow.',
        'plugin.btn.pricing': 'View Pricing',
        'plugin.btn.download': 'Download Free',
        'plugin.feat1.title': 'Dual Display',
        'plugin.feat1.desc': 'Automatically shows the EUR equivalent next to your BGN prices using the fixed exchange rate (1.95583).',
        'plugin.feat2.title': 'Compliance Ready',
        'plugin.feat2.desc': 'Adds the required legal disclaimer about the official BNB exchange rate to your cart and emails.',
        'plugin.feat3.title': 'Bulk Converter',
        'plugin.feat3.desc': 'Securely convert thousands of products in your database with rounding rules when the time comes.',
        'plugin.pricing.title': 'Simple Licensing',
        'plugin.plan.free.title': 'Community Choice',
        'plugin.plan.free.desc': 'For small shops and testing.',
        'plugin.plan.free.price': 'Free',
        'plugin.feat.dual': 'Dual Price Display',
        'plugin.feat.disclaimer': 'Legal Disclaimers',
        'plugin.feat.convert20': 'Convert up to 20 Products',
        'plugin.btn.download_plugin': 'Download Plugin',
        'plugin.plan.pro.rec': 'RECOMMENDED',
        'plugin.plan.pro.title': 'Professional',
        'plugin.plan.pro.desc': 'For serious e-commerce businesses.',
        'plugin.plan.pro.period': '/ one-time',
        'plugin.feat.unlimited': 'Unlimited Conversions',
        'plugin.feat.rounding': 'Custom Rounding Rules',
        'plugin.feat.support': 'Priority Email Support',
        'plugin.feat.domain': 'Single Domain License',
        'plugin.btn.buy': 'Buy Now',
        'plugin.beta': 'Currently in private beta. Contact us for bulk agency licenses.',
        'plugin.case_study': 'Read Engineering Case Study',
        'nav.portfolio': 'WP Portfolio',
        'portfolio.title.prefix': 'WordPress',
        'portfolio.title.suffix': 'Portfolio',
        'portfolio.desc': 'A selection of WordPress projects showcasing custom theme development, plugin integration, and performance optimization.',
        'portfolio.project1.title': 'Client Project A',
        'portfolio.project1.desc': 'Custom theme development for a corporate client.',
        'portfolio.project2.title': 'e-Commerce Site B',
        'portfolio.project2.desc': 'WooCommerce integration with custom checkout flow.',
        'portfolio.project3.title': 'Blog Portal C',
        'portfolio.project3.desc': 'High-traffic content portal with ad-network integration.',
        'portfolio.hotel.title': 'Hotel Booking Template',
        'portfolio.hotel.desc': 'A complete hotel booking system template with Bulgarian localization and premium forest green theme.',
    },
    bg: {
        'nav.about': 'За Мен',
        'nav.products': 'Продукти',
        'nav.lab': 'Лабораторията',
        'nav.work_with_us': 'Работете с нас',
        'hero.title.prefix': 'Архитект на',
        'hero.title.suffix': 'Дигитални Проекти',
        'hero.led_by': 'Водено от Калин Димитров',
        'hero.description': 'Invent2025 е <strong>Лаборатория за Продуктово Инженерство</strong>, която свързва академичните изследвания с доказани Angular SaaS решения. Ние изграждаме мащабируеми платформи за бъдещето.',
        'hero.learn_more': 'Научете повече за Калин →',
        'services.title': 'Услуги за Клиенти',
        'services.architecture.title': 'Системна Архитектура',
        'services.architecture.desc': 'Оптимизация на мащабни Angular/Nx монорепозитора.',
        'services.mvp.title': 'MVP Разработка',
        'services.mvp.desc': 'Пълен цикъл: Дизайн, Код, Внедряване.',
        'ventures.title': 'Нашите Проекти',
        'ventures.subtitle': 'SAAS & PLUGINS',
        'ventures.view_all': 'Виж Всички →',
        'ventures.inviteathon.desc': 'B2B SaaS за Парти Центрове.',
        'ventures.inviteathon.users': '10,000+ Потребители',
        'ventures.inviteathon.live': 'НА ЖИВО',
        'ventures.ascendpass.desc': 'Членска система активна с реални клиенти.',
        'ventures.ascendpass.live': 'LIVE SAAS',
        'ventures.plugin.desc': 'Автоматизирана миграция на бази данни и двойно ценообразуване за WooCommerce.',
        'ascendpass.status.live': 'Активен в Продукция',
        'ascendpass.subtitle': 'Членства и Абонаменти',
        'ascendpass.platform.title': 'Платформата',
        'ascendpass.platform.desc': 'Управлението на периодични приходи и контрол на достъпа изисква изключителна надеждност. AscendPass е цялостно решение за управление на членства, което вече захранва работещи бизнеси.',
        'ascendpass.platform.desc2': 'Той управлява целия жизнен цикъл: от момента на регистрация на потребителя, през месечните периодични плащания, до ролевия контрол на достъпа в клиентското приложение.',
        'ascendpass.billing.title': 'Автоматизирани Плащания',
        'ascendpass.billing.desc': 'Дълбока интеграция със Stripe за възстановяване на неуспешни плащания, про-ретиране и ъпгрейди.',
        'ascendpass.rbac.title': 'RBAC & Auth',
        'ascendpass.rbac.desc': 'Грануларни обхвати на правата, които се синхронизират мигновено със статуса на абонамента.',
        'ventures.view_case_study': 'Виж Case Study →',
        'ventures.view_platform': 'Виж Платформата →',
        'ventures.view_product': 'Виж Продукта →',
        'lab.title': 'От Лабораторията',
        'lab.view_all': 'Виж Всички →',
        'lab.case_study': 'Case Study',
        'lab.engineering': 'Engineering',
        'lab.research': 'Research',
        'cta.title': "Да градим заедно.",
        'cta.subtitle': 'Имате нужда от Системен Архитект?',
        'cta.button': 'Запиши час',
        'footer.rights': 'Всички права запазени.',
        'plugin.hero.tag': 'WOOCOMMERCE ПЛЪГИН',
        'plugin.hero.title': 'Подгответе се за Еврото.',
        'plugin.hero.desc': 'Автоматизирайте прехода на вашия магазин от BGN към EUR с фиксиран курс на БНБ. Показвайте двойни цени днес, конвертирайте ефективно утре.',
        'plugin.btn.pricing': 'Виж Цени',
        'plugin.btn.download': 'Свали Безплатно',
        'plugin.feat1.title': 'Двойно Показване',
        'plugin.feat1.desc': 'Автоматично показва еквивалента в EUR до вашите цени в BGN, използвайки фиксирания курс (1.95583).',
        'plugin.feat2.title': 'Готов за Compliance',
        'plugin.feat2.desc': 'Добавя задължителния правен текст за официалния курс на БНБ във вашата количка и имейли.',
        'plugin.feat3.title': 'Масов Конвертор',
        'plugin.feat3.desc': 'Сигурно конвертиране на хиляди продукти във вашата база данни с правила за закръгляне, когато му дойде времето.',
        'plugin.pricing.title': 'Лицензиране',
        'plugin.plan.free.title': 'Community Choice',
        'plugin.plan.free.desc': 'За малки магазини и тестове.',
        'plugin.plan.free.price': 'Безплатно',
        'plugin.feat.dual': 'Двойни Цени',
        'plugin.feat.disclaimer': 'Правни Текстове',
        'plugin.feat.convert20': 'Конвертирай до 20 продукта',
        'plugin.btn.download_plugin': 'Свали Плъгина',
        'plugin.plan.pro.rec': 'ПРЕПОРЪЧАНО',
        'plugin.plan.pro.title': 'Professional',
        'plugin.plan.pro.desc': 'За сериозни онлайн магазини.',
        'plugin.plan.pro.period': '/ еднократно',
        'plugin.feat.unlimited': 'Неограничени Конверсии',
        'plugin.feat.rounding': 'Правила за Закръгляне',
        'plugin.feat.support': 'Приоритетна Поддръжка',
        'plugin.feat.domain': 'Лиценз за 1 Домейн',
        'plugin.btn.buy': 'Купи Сега',
        'plugin.beta': 'В момента е в частна бета. Свържете се с нас за лицензи за агенции.',
        'plugin.case_study': 'Прочети Инженерното Case Study',

        'nav.portfolio': 'WP Портфолио',
        'portfolio.title.prefix': 'WordPress',
        'portfolio.title.suffix': 'Портфолио',
        'portfolio.desc': 'Селекция от WordPress проекти, показващи разработка на персонализирани теми, интеграция на плъгини и оптимизация на производителността.',
        'portfolio.project1.title': 'Клиентски Проект А',
        'portfolio.project1.desc': 'Разработка на персонализирана тема за корпоративен клиент.',
        'portfolio.project2.title': 'Електронен Магазин Б',
        'portfolio.project2.desc': 'WooCommerce интеграция с персонализиран checkout процес.',
        'portfolio.project3.title': 'Блог Портал В',
        'portfolio.project3.desc': 'Портал за съдържание с висок трафик и интеграция на рекламни мрежи.',
        'portfolio.hotel.title': 'Шаблон за Хотелски Резервации',
        'portfolio.hotel.desc': 'Пълен шаблон за система за хотелски резервации с локализация на български и премиум горско зелена тема.',
    },
};
